/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AgentPanel: typeof import('./../components/AgentPanel.vue')['default']
    AppLayout: typeof import('./../components/AppLayout.vue')['default']
    ChartCard: typeof import('./../components/ChartCard.vue')['default']
    ConfirmExecModal: typeof import('./../components/ConfirmExecModal.vue')['default']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    ObjectTree: typeof import('./../components/ObjectTree.vue')['default']
    ResultTable: typeof import('./../components/ResultTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SqlEditor: typeof import('./../components/SqlEditor.vue')['default']
  }
}
