-- ?????????? - ???? (Oracle Free)
-- ??: ? SYSTEM ?????1?(??, ??????); ???? BANK ?????????
-- ???????: export NLS_LANG=AMERICAN_AMERICA.AL32UTF8 (Linux) ? set NLS_LANG=AMERICAN_AMERICA.AL32UTF8 (Windows)

-- ============ 1. ??????(??, ? SYSTEM ??) ============
BEGIN
    EXECUTE IMMEDIATE 'CREATE USER BANK IDENTIFIED BY "Bank123456"';
    EXECUTE IMMEDIATE 'GRANT CONNECT, RESOURCE TO BANK';
    EXECUTE IMMEDIATE 'ALTER USER BANK DEFAULT TABLESPACE USERS';
    EXECUTE IMMEDIATE 'ALTER USER BANK QUOTA UNLIMITED ON USERS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -1920 THEN NULL; ELSE RAISE; END IF;
END;
/

-- ============ 2. ?????(?????) ============
BEGIN EXECUTE IMMEDIATE 'DROP TABLE T_TRANS_LOG CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE T_TRANS_CONFIG CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE T_ACCOUNT CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE T_USER CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE T_ORG CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_T_TRANS_LOG'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF; END;
/

-- ============ 3. ?? ============
CREATE TABLE T_ORG (
        ORG_ID        NUMBER(10)    NOT NULL,
        ORG_NAME      VARCHAR2(100) NOT NULL,
        ORG_LEVEL     VARCHAR2(20)  NOT NULL,
        PARENT_ORG_ID NUMBER(10),
        ORG_TYPE      VARCHAR2(30)  NOT NULL,
        REGION        VARCHAR2(30),
        STATUS        VARCHAR2(10)  DEFAULT 'ACTIVE' NOT NULL,
        CREATED_AT    DATE          DEFAULT SYSDATE NOT NULL,
        CONSTRAINT PK_T_ORG PRIMARY KEY (ORG_ID),
        CONSTRAINT FK_T_ORG_PARENT FOREIGN KEY (PARENT_ORG_ID) REFERENCES T_ORG (ORG_ID)
    );

CREATE TABLE T_USER (
        USER_ID    NUMBER(12)   NOT NULL,
        USER_NO    VARCHAR2(20) NOT NULL,
        USER_NAME  VARCHAR2(100) NOT NULL,
        CERT_TYPE  VARCHAR2(10) NOT NULL,
        CERT_NO    VARCHAR2(32) NOT NULL,
        GENDER     VARCHAR2(2),
        BIRTH_DATE DATE,
        PHONE      VARCHAR2(20),
        EMAIL      VARCHAR2(64),
        ADDRESS    VARCHAR2(200),
        RISK_LEVEL VARCHAR2(10) DEFAULT 'LOW' NOT NULL,
        USER_TYPE  VARCHAR2(10) DEFAULT 'PERSONAL' NOT NULL,
        ORG_ID     NUMBER(10)   NOT NULL,
        STATUS     VARCHAR2(10) DEFAULT 'ACTIVE' NOT NULL,
        CREATED_AT DATE         DEFAULT SYSDATE NOT NULL,
        UPDATED_AT DATE,
        CONSTRAINT PK_T_USER PRIMARY KEY (USER_ID),
        CONSTRAINT UK_T_USER_NO UNIQUE (USER_NO),
        CONSTRAINT UK_T_USER_CERT UNIQUE (CERT_TYPE, CERT_NO),
        CONSTRAINT FK_T_USER_ORG FOREIGN KEY (ORG_ID) REFERENCES T_ORG (ORG_ID)
    );

CREATE TABLE T_ACCOUNT (
        ACCOUNT_ID        NUMBER(14)    NOT NULL,
        ACCOUNT_NO        VARCHAR2(32)  NOT NULL,
        USER_ID           NUMBER(12)    NOT NULL,
        ORG_ID            NUMBER(10)    NOT NULL,
        ACCOUNT_TYPE      VARCHAR2(20)  NOT NULL,
        CURRENCY          VARCHAR2(3)   DEFAULT 'CNY' NOT NULL,
        BALANCE           NUMBER(18,2)  DEFAULT 0 NOT NULL,
        AVAILABLE_BALANCE NUMBER(18,2)  DEFAULT 0 NOT NULL,
        OPEN_DATE         DATE          NOT NULL,
        STATUS            VARCHAR2(10)  DEFAULT 'ACTIVE' NOT NULL,
        CONSTRAINT PK_T_ACCOUNT PRIMARY KEY (ACCOUNT_ID),
        CONSTRAINT UK_T_ACCOUNT_NO UNIQUE (ACCOUNT_NO),
        CONSTRAINT FK_T_ACCOUNT_USER FOREIGN KEY (USER_ID) REFERENCES T_USER (USER_ID),
        CONSTRAINT FK_T_ACCOUNT_ORG FOREIGN KEY (ORG_ID) REFERENCES T_ORG (ORG_ID)
    );

CREATE TABLE T_TRANS_CONFIG (
        CONFIG_ID    NUMBER(10)    NOT NULL,
        TRANS_CODE   VARCHAR2(20)  NOT NULL,
        TRANS_NAME   VARCHAR2(100) NOT NULL,
        CHANNEL      VARCHAR2(20)  NOT NULL,
        TRANS_TYPE   VARCHAR2(20)  NOT NULL,
        FEE_RATE     NUMBER(10,6)  DEFAULT 0 NOT NULL,
        FEE_MIN      NUMBER(10,2)  DEFAULT 0 NOT NULL,
        FEE_MAX      NUMBER(10,2)  DEFAULT 0 NOT NULL,
        SINGLE_LIMIT NUMBER(18,2),
        DAILY_LIMIT  NUMBER(18,2),
        STATUS       VARCHAR2(10)  DEFAULT 'ACTIVE' NOT NULL,
        UPDATED_AT   DATE          DEFAULT SYSDATE NOT NULL,
        CONSTRAINT PK_T_TRANS_CONFIG PRIMARY KEY (CONFIG_ID),
        CONSTRAINT UK_T_TRANS_CONFIG_CODE UNIQUE (TRANS_CODE)
    );

CREATE TABLE T_TRANS_LOG (
        LOG_ID             NUMBER(16)    NOT NULL,
        TRANS_SERIAL_NO    VARCHAR2(40)  NOT NULL,
        TRANS_CODE         VARCHAR2(20)  NOT NULL,
        CHANNEL            VARCHAR2(20)  NOT NULL,
        TRANS_TYPE         VARCHAR2(20)  NOT NULL,
        ACCOUNT_NO         VARCHAR2(32)  NOT NULL,
        COUNTER_ACCOUNT_NO VARCHAR2(32),
        AMOUNT             NUMBER(18,2)  NOT NULL,
        FEE                NUMBER(10,2)  DEFAULT 0 NOT NULL,
        STATUS             VARCHAR2(10)  DEFAULT 'SUCCESS' NOT NULL,
        TRANS_TIME         DATE          NOT NULL,
        ORG_ID             NUMBER(10),
        USER_ID            NUMBER(12),
        REMARK             VARCHAR2(200),
        CONSTRAINT PK_T_TRANS_LOG PRIMARY KEY (LOG_ID),
        CONSTRAINT UK_T_TRANS_SERIAL UNIQUE (TRANS_SERIAL_NO),
        CONSTRAINT FK_T_LOG_ACCOUNT FOREIGN KEY (ACCOUNT_NO) REFERENCES T_ACCOUNT (ACCOUNT_NO),
        CONSTRAINT FK_T_LOG_ORG FOREIGN KEY (ORG_ID) REFERENCES T_ORG (ORG_ID),
        CONSTRAINT FK_T_LOG_USER FOREIGN KEY (USER_ID) REFERENCES T_USER (USER_ID)
    );

-- ============ 4. ??/??/?? ============
CREATE INDEX IDX_T_USER_ORG ON T_USER (ORG_ID);
CREATE INDEX IDX_T_ACCOUNT_USER ON T_ACCOUNT (USER_ID);
CREATE INDEX IDX_T_ACCOUNT_ORG ON T_ACCOUNT (ORG_ID);
CREATE INDEX IDX_T_LOG_TIME ON T_TRANS_LOG (TRANS_TIME);
CREATE INDEX IDX_T_LOG_ACCOUNT ON T_TRANS_LOG (ACCOUNT_NO);
CREATE INDEX IDX_T_LOG_CODE ON T_TRANS_LOG (TRANS_CODE);
CREATE INDEX IDX_T_LOG_ORG_TIME ON T_TRANS_LOG (ORG_ID, TRANS_TIME);
CREATE SEQUENCE SEQ_T_TRANS_LOG START WITH 1 INCREMENT BY 1 NOCACHE;

COMMENT ON TABLE T_ORG IS '机构表：银行总行/分行/支行/网点组织架构';
COMMENT ON COLUMN T_ORG.ORG_ID IS '机构号';
COMMENT ON COLUMN T_ORG.ORG_NAME IS '机构名称';
COMMENT ON COLUMN T_ORG.ORG_LEVEL IS '机构层级(HEAD/BRANCH/SUB_BRANCH/POINT)';
COMMENT ON COLUMN T_ORG.PARENT_ORG_ID IS '上级机构号';
COMMENT ON COLUMN T_ORG.ORG_TYPE IS '机构类型';
COMMENT ON COLUMN T_ORG.REGION IS '所在地区';
COMMENT ON COLUMN T_ORG.STATUS IS '状态(ACTIVE/INACTIVE)';
COMMENT ON COLUMN T_ORG.CREATED_AT IS '创建时间';
COMMENT ON TABLE T_USER IS '用户表：个人客户与企业客户基础信息';
COMMENT ON COLUMN T_USER.USER_ID IS '用户ID';
COMMENT ON COLUMN T_USER.USER_NO IS '客户编号';
COMMENT ON COLUMN T_USER.USER_NAME IS '客户名称';
COMMENT ON COLUMN T_USER.CERT_TYPE IS '证件类型(ID身份证/USCC统一社会信用代码)';
COMMENT ON COLUMN T_USER.CERT_NO IS '证件号码';
COMMENT ON COLUMN T_USER.GENDER IS '性别(M男/F女)';
COMMENT ON COLUMN T_USER.BIRTH_DATE IS '出生日期';
COMMENT ON COLUMN T_USER.PHONE IS '联系电话';
COMMENT ON COLUMN T_USER.EMAIL IS '电子邮箱';
COMMENT ON COLUMN T_USER.ADDRESS IS '联系地址';
COMMENT ON COLUMN T_USER.RISK_LEVEL IS '风险等级(LOW/MEDIUM/HIGH)';
COMMENT ON COLUMN T_USER.USER_TYPE IS '客户类型(PERSONAL个人/CORP企业)';
COMMENT ON COLUMN T_USER.ORG_ID IS '开户机构号';
COMMENT ON COLUMN T_USER.STATUS IS '状态(ACTIVE/INACTIVE)';
COMMENT ON COLUMN T_USER.CREATED_AT IS '建档时间';
COMMENT ON COLUMN T_USER.UPDATED_AT IS '更新时间';
COMMENT ON TABLE T_ACCOUNT IS '账户表：客户在银行开立的账户及余额';
COMMENT ON COLUMN T_ACCOUNT.ACCOUNT_ID IS '账户ID';
COMMENT ON COLUMN T_ACCOUNT.ACCOUNT_NO IS '账号/卡号';
COMMENT ON COLUMN T_ACCOUNT.USER_ID IS '所属用户ID';
COMMENT ON COLUMN T_ACCOUNT.ORG_ID IS '开户机构号';
COMMENT ON COLUMN T_ACCOUNT.ACCOUNT_TYPE IS '账户类型(SAVINGS/CHECKING/FINANCE/CORP_BASIC/CORP_GEN)';
COMMENT ON COLUMN T_ACCOUNT.CURRENCY IS '币种';
COMMENT ON COLUMN T_ACCOUNT.BALANCE IS '账户余额';
COMMENT ON COLUMN T_ACCOUNT.AVAILABLE_BALANCE IS '可用余额';
COMMENT ON COLUMN T_ACCOUNT.OPEN_DATE IS '开户日期';
COMMENT ON COLUMN T_ACCOUNT.STATUS IS '状态(ACTIVE/FROZEN/CLOSED)';
COMMENT ON TABLE T_TRANS_CONFIG IS '交易配置表：交易产品、渠道、费率与限额配置';
COMMENT ON COLUMN T_TRANS_CONFIG.CONFIG_ID IS '配置ID';
COMMENT ON COLUMN T_TRANS_CONFIG.TRANS_CODE IS '交易码';
COMMENT ON COLUMN T_TRANS_CONFIG.TRANS_NAME IS '交易名称';
COMMENT ON COLUMN T_TRANS_CONFIG.CHANNEL IS '交易渠道(COUNTER/ATM/ONLINE/MOBILE/POS/AUTO/INTERNET)';
COMMENT ON COLUMN T_TRANS_CONFIG.TRANS_TYPE IS '交易类型(DEPOSIT/WITHDRAW/TRANSFER/PAYMENT/FINANCE/LOAN/REPAY/FX)';
COMMENT ON COLUMN T_TRANS_CONFIG.FEE_RATE IS '费率';
COMMENT ON COLUMN T_TRANS_CONFIG.FEE_MIN IS '最低手续费';
COMMENT ON COLUMN T_TRANS_CONFIG.FEE_MAX IS '最高手续费';
COMMENT ON COLUMN T_TRANS_CONFIG.SINGLE_LIMIT IS '单笔限额';
COMMENT ON COLUMN T_TRANS_CONFIG.DAILY_LIMIT IS '日累计限额';
COMMENT ON COLUMN T_TRANS_CONFIG.STATUS IS '状态(ACTIVE/INACTIVE)';
COMMENT ON COLUMN T_TRANS_CONFIG.UPDATED_AT IS '更新时间';
COMMENT ON TABLE T_TRANS_LOG IS '业务流水表：每笔交易的流水明细记录';
COMMENT ON COLUMN T_TRANS_LOG.LOG_ID IS '流水ID';
COMMENT ON COLUMN T_TRANS_LOG.TRANS_SERIAL_NO IS '交易流水号';
COMMENT ON COLUMN T_TRANS_LOG.TRANS_CODE IS '交易码';
COMMENT ON COLUMN T_TRANS_LOG.CHANNEL IS '交易渠道';
COMMENT ON COLUMN T_TRANS_LOG.TRANS_TYPE IS '交易类型';
COMMENT ON COLUMN T_TRANS_LOG.ACCOUNT_NO IS '本方账号';
COMMENT ON COLUMN T_TRANS_LOG.COUNTER_ACCOUNT_NO IS '对方账号';
COMMENT ON COLUMN T_TRANS_LOG.AMOUNT IS '交易金额';
COMMENT ON COLUMN T_TRANS_LOG.FEE IS '手续费';
COMMENT ON COLUMN T_TRANS_LOG.STATUS IS '交易状态(SUCCESS/PENDING/FAIL)';
COMMENT ON COLUMN T_TRANS_LOG.TRANS_TIME IS '交易时间';
COMMENT ON COLUMN T_TRANS_LOG.ORG_ID IS '交易机构号';
COMMENT ON COLUMN T_TRANS_LOG.USER_ID IS '用户ID';
COMMENT ON COLUMN T_TRANS_LOG.REMARK IS '备注';

-- ????